name: Build test on PR

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: Check TypeScript version
        run: npx tsc --version

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: 📥 Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
          run_install: true

      - name: 🧹 Lint the code
        run: pnpm run lint

      - name: 🔧 Build the project
        run: pnpm run build
